CREATE TABLE users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(60),
	hash VARCHAR(40) UNIQUE,
	balance FLOAT
);

CREATE TABLE products (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	barcode VARCHAR(40) UNIQUE,
	price FLOAT,
	name VARCHAR(255)
);
INSERT INTO products VALUES (1,NULL,NULL,'Deposit');

CREATE TABLE log (
	dt VARCHAR(23),
	uid INTEGER,
	pid INTEGER,
	count INTEGER,
	price FLOAT
);
